name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-std:
    name: "Test (std)"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Rust dependency cache
      uses: Swatinem/rust-cache@v2
    - name: Compile and run tests
      run: cargo test --no-fail-fast

  test-no-std:
    name: "Test (no_std)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test --no-fail-fast --lib --no-default-features
